modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/IAFEnvoy/ResourceWorld/issues"
license = "All Right Reserved"

[[mods]]
modId = "resource_world"
version = "${version}"
displayName = "Resource World"
authors = "IAFEnvoy"
description = '''
A server side mod to create resource worlds
'''
logoFile = "logo.png"

[[dependencies.resource_world]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resource_world]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.5)"
ordering = "NONE"
side = "BOTH"
