modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CodeOfArdonia/ResourceWorld/issues"
license = "All Right Reserved"

[[mods]]
modId = "resource_world"
version = "${version}"
displayName = "Resource World"
authors = "IAFEnvoy"
description = '''
A server side mod to create resource worlds
'''
logoFile = "logo.png"

[[dependencies.resource_world]]
modId = "neoforge"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resource_world]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resource_world]]
modId = "server_i18n_api"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "resource_world.mixins.json"